judge/urls.py
from django.conf.urls import url, include
from .views import  select_point, delete_problem, add_problem, ProblemDetailView, update_problem, \
    add_choice, list_problems,list_choices,del_choice_problem,ChoiceProblemDetailView,update_choice_problem, verify_file

urlpatterns = [
    url(r'problem_list/$', list_problems, name='problemlist'),
    url(r'choice_problem_list',list_choices,name='choice_problem_list'),
    url(r'^del-problem/$', delete_problem, name='del_problem'),
    url(r'^del-choice-problem',del_choice_problem,name='del_choice_problem'),
    url(r'add-problem', add_problem, name='add_problem'),
    url(r'pointslect', select_point, name='select_point'),
    url(r'^problem-detail-$', ProblemDetailView.as_view(), name='_problem_detail'),
    url(r'^choice-detail-$',ChoiceProblemDetailView.as_view(),name='_choice_problem_detail'),
    url(r'^update-biancheng-$', update_problem, name='_update_problem'),
    url(r'update-choice-$',update_choice_problem,name='_update_choice_problem'),
    url(r'^problem-detail-(?P<pk>\d+)/$', ProblemDetailView.as_view(), name='problem_detail'),
    url(r'^choice-detail-(?P<pk>\d+)/$',ChoiceProblemDetailView.as_view(),name='choice_problem_detail'),
    url(r'^update-biancheng-(?P<id>\d*)/$', update_problem, name='update_problem'),
    url(r'update-choice-(?P<id>\d+)/$',update_choice_problem,name='update_choice_problem'),
    url(r'add-choice', add_choice, name='add_choice_problem'),
    url(r'verify-file',verify_file,name='verify_file'),
]

onlineTest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from judge.views import get_json

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='adminView'),
    url(r'^index/', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include('auth_system.urls')),
    url(r'^judge/', include('judge.urls')),
    url(r'^work/', include('work.urls')),
    url(r'get-json-(?P<model_name>\w+)/$', get_json,name='get_json'),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    
]

work/urls.py
from django.conf.urls import url, include

from work.views import add_homework, get_json_work, list_homework, del_homework, show_homework, \
    ajax_for_homework_info, do_homework, add_banji, add_courser, get_banji_list, list_banji, del_banji, update_banji, \
    copy_to_my_homework, list_my_homework, update_public_homework, update_my_homework, show_my_homework, show_banji, \
    add_students, ajax_add_students, assign_homework, list_do_homework, get_my_homework_todo, show_homework_result, \
    list_finished_homework, get_finished_homework, get_finished_students, list_coursers, list_kp1s, list_kp2s, \
    delete_courser, add_kp1, add_kp2, delete_kp1, delete_kp2, add_myhomework, test_run, delete_homeworkanswer, \
    rejudge_homework, save_homework_temp, init_homework_data, file_download

urlpatterns = [
    url(r'del-homeworkanswer-(?P<id>\d+)', delete_homeworkanswer, name='delete_homeworkanswer'),
    url(r'del-homeworkanswer-', delete_homeworkanswer, name='_delete_homeworkanswer'),
    url(r'add-homework$', add_homework, name='add_homework'),
    url(r'get-json-work', get_json_work, name='get_json_data'),
    url(r'^homework-list', list_homework, name='homework_list'),
    url(r'del-homework', del_homework, name='del_homework'),
    url(r'^homework-detail-$', show_homework, name='_homework_detail'),
    url(r'update-public-homework-$', update_public_homework, name='_update_public_homework'),
    url(r'update-my-homework-$', update_my_homework, name='_update_my_homework'),
    url(r'do_homework$', do_homework, name='_do_homework'),
    url(r'update-banji-$', update_banji, name='_update_banji'),
    url(r'my-homework-detail-$', show_my_homework, name='_my_homework_detail'),
    url(r'banji-detail-$', show_banji, name='_banji_detail'),
    url(r'add-students-to-mybanji-$', add_students, name='_add_students'),
    url(r'homework-result-$', show_homework_result, name='_show_homework_result'),
    url(r'^homework-detail-(?P<pk>\d+)/$', show_homework, name='homework_detail'),
    url(r'update-public-homework-(?P<pk>\d+)', update_public_homework, name='update_public_homework'),
    url(r'update-my-homework-(?P<pk>\d+)', update_my_homework, name='update_my_homework'),
    url(r'get_homework_info', ajax_for_homework_info, name='get_homework_info'),
    url(r'do_homework(?P<homework_id>\d+)', do_homework, name='do_homework'),
    url(r'add_banji', add_banji, name='add_banji'),
    url(r'add_courser', add_courser, name='add_courser'),
    url(r'get_banji_list', get_banji_list, name='get_banji_list'),
    url(r'banji-list', list_banji, name='banji_list'),
    url(r'del-banji', del_banji, name='del_banji'),
    url(r'update-banji-(?P<id>\d+)', update_banji, name='update_banji'),
    url(r'copy-to-myhomework', copy_to_my_homework, name='copy_to_my_homework'),
    url(r'my_homework_list', list_my_homework, name='my_homework_list'),
    url(r'my-homework-detail-(?P<pk>\d+)', show_my_homework, name='my_homework_detail'),
    url(r'banji-detail-(?P<pk>\d+)', show_banji, name='banji_detail'),
    url(r'add-students-to-mybanji-(?P<pk>\d+)', add_students, name='add_students'),
    url(r'add-students', ajax_add_students, name='ajax_add_students'),
    url(r'assign-homework', assign_homework, name='assign_homework'),
    url(r'do-homework-list', list_do_homework, name='list_do_homework'),
    url(r'get-do-homework-data', get_my_homework_todo, name='get_my_homework_todo'),
    url(r'homework-result-(?P<id>\d+)', show_homework_result, name='show_homework_result'),
    url(r'list-finished-homework', list_finished_homework, name='list_finished_homework'),
    url(r'get-finished-homework-list', get_finished_homework, name='get_finished_homework'),
    url(r'get-finished-student', get_finished_students, name="get_finished_students"),
    url(r'courser-list', list_coursers, name='list_coursers'),
    url(r'kp1-list-(?P<id>\d+)', list_kp1s, name='list_kp1s'),
    url(r'kp2-list-(?P<id>\d+)', list_kp2s, name='list_kp2s'),
    url(r'delete-courser', delete_courser, name='delete_courser'),
    url(r'add-kp1', add_kp1, name='add_kp1'),
    url(r'add-kp2', add_kp2, name='add_kp2'),
    url(r'delete-kp1', delete_kp1, name='delete_kp1'),
    url(r'delete-kp2', delete_kp2, name='delete_kp2'),
    url(r'add-myhomework', add_myhomework, name='add_myhomework'),
    url(r'test_run', test_run, name='test_run'),
    url(r'rejudge-homework-$', rejudge_homework, name='_rejudge_homework'),
    url(r'rejudge-homework-(?P<id>\d+)', rejudge_homework, name='rejudge_homework'),
    url(r'save-homework',save_homework_temp,name='save_homework'),
    url(r'get-init-homework-data',init_homework_data,name='get_init_homework_data'),
    url(r'download',file_download,name='download')
]

judge/models.py
from django.db import models

from auth_system.models import MyUser

# Create your models here.
from work.models import HomeworkAnswer, MyHomework


class ClassName(models.Model):
    name = models.CharField(verbose_name='课程名称', max_length=30)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'class_name'
        verbose_name = '课程名称'
        verbose_name_plural = '课程名称'


class KnowledgePoint1(models.Model):
    name = models.CharField(verbose_name='一级知识点名称', max_length=20)
    id = models.AutoField(primary_key=True)
    classname = models.ForeignKey(ClassName, verbose_name='所属课程')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'knowledge_point_1'
        verbose_name = '一级知识点'
        verbose_name_plural = '一级知识点'


class KnowledgePoint2(models.Model):
    name = models.CharField(verbose_name='二级知识点名称', max_length=20)
    upperPoint = models.ForeignKey(KnowledgePoint1, verbose_name='上级课程')
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'knowledge_point_2'
        verbose_name = '二级知识点'
        verbose_name_plural = '二级知识点'


class ChoiceProblem(models.Model):
    id = models.AutoField('选择题ID', primary_key=True)
    title = models.TextField(max_length=200)
    a = models.CharField(max_length=50)
    b = models.CharField(max_length=50)
    c = models.CharField(max_length=50)
    d = models.CharField(max_length=50)
    right_answer = models.CharField(max_length=1)
    creater = models.ForeignKey(MyUser)
    update_date = models.DateTimeField(auto_now=True, verbose_name='最后修改时间', blank=True, null=True)
    in_date = models.DateTimeField(auto_now_add=True)
    knowledgePoint1 = models.ManyToManyField(KnowledgePoint1, verbose_name='一级知识点')
    knowledgePoint2 = models.ManyToManyField(KnowledgePoint2, verbose_name='二级知识点')
    classname = models.ManyToManyField(ClassName, verbose_name='所属课程')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['id']
        verbose_name = '选择题'
        verbose_name_plural = '选择题'


class Problem(models.Model):
    problem_id = models.AutoField('题目id', primary_key=True)
    title = models.CharField(verbose_name='标题', max_length=200)
    description = models.TextField('描述', blank=True, null=True)
    input = models.TextField('输入描述', blank=True, null=True)
    output = models.TextField('输出描述', blank=True, null=True)
    sample_input = models.TextField('样例输入1', blank=True, null=True)
    sample_output = models.TextField('样例输出1', blank=True, null=True)
    sample_input2 = models.TextField('样例输入2', blank=True, null=True)
    sample_output2 = models.TextField('样例输出2', blank=True, null=True)
    spj = models.CharField(max_length=1, default=0)
    hint = models.TextField(blank=True, null=True)
    source = models.CharField(max_length=100, blank=True, null=True)
    in_date = models.DateTimeField('录入时间', blank=True, null=True, auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True, verbose_name='最后修改时间', blank=True, null=True)
    time_limit = models.IntegerField('限制时间', default=1)
    memory_limit = models.IntegerField('限制内存', default=128)
    defunct = models.CharField(max_length=1, default='N')
    accepted = models.IntegerField('AC数量', blank=True, null=True, default=0)
    submit = models.IntegerField('提交数量', blank=True, null=True, default=0)
    solved = models.IntegerField(blank=True, null=True)
    knowledgePoint1 = models.ManyToManyField(KnowledgePoint1, verbose_name='一级知识点')
    knowledgePoint2 = models.ManyToManyField(KnowledgePoint2, verbose_name='二级知识点')
    classname = models.ManyToManyField(ClassName, verbose_name='所属课程')
    creater = models.ForeignKey(MyUser)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'problem'
        ordering = ['problem_id']
        verbose_name = '编程题'
        verbose_name_plural = '编程题'


class Runtimeinfo(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    error = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'runtimeinfo'


class Solution(models.Model):
    solution_id = models.AutoField(primary_key=True)
    problem_id = models.IntegerField()
    user_id = models.CharField(max_length=48)
    time = models.IntegerField(default=0)
    memory = models.IntegerField(default=0)
    in_date = models.DateTimeField(auto_now_add=True)
    result = models.SmallIntegerField(default=0)
    language = models.IntegerField(default=0)
    ip = models.CharField(max_length=15)
    contest_id = models.IntegerField(blank=True, null=True)
    valid = models.IntegerField(default=1)
    num = models.IntegerField(default=-1)
    code_length = models.IntegerField(default=0)
    judgetime = models.DateTimeField(blank=True, null=True)
    pass_rate = models.DecimalField(max_digits=2, decimal_places=2, default=0.00)
    lint_error = models.IntegerField(default=0)
    homework_answer = models.ForeignKey(HomeworkAnswer, null=True)
    oi_info = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'solution'

    def __str__(self):
        try:
            return str(self.homework_answer.id)
        except:
            return 'none'


class SourceCode(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    source = models.TextField()

    class Meta:
        db_table = 'source_code'

    def __str__(self):
        return str(self.solution_id)


class SourceCodeUser(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    source = models.TextField()

    class Meta:
        db_table = 'source_code_user'


class Compileinfo(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    error = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'compileinfo'

judge/templates/choice_problem_add.html
{% extends 'base.html' %}
{% block extrahead %}
    {% load static %}
    <script src="{% static 'assets/js/bootstrap-tagsinput.min.js' %}"></script>
    <link href="{% static 'assets/css/bootstrap-tagsinput-typeahead.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap-tagsinput.css' %}" rel="stylesheet">
    <script src="{% static 'assets/js/jquery.form-validator.min.js' %}"></script>
{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li class="active"><a href="{% url 'choice_problem_list' %}"></a>选择题题库管理</li>
        <li class="active">{{ title }}</li>
    </ol>
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group {% if form.title.errors %} has-error {% endif %}">
                    <label class="control-label"
                           for="{% if form.title.errors %} inputError1 {% endif %}">{{ form.title.label }}</label>
                    {% if form.title.errors %}
                        <span class="text-danger pull-right">{{ form.title.errors }}</span>
                    {% endif %}
                    {{ form.title }}
                    <p class="text-muted">{{ form.title.help_text }}</p>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-xs-6">
                        <div class="input-group">
                             <span class="input-group-addon">
                               {{ form.selection.0 }}
                                </span>
                            {{ form.a }}
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-xs-6">
                        <div class="input-group">
                             <span class="input-group-addon">
                                {{ form.selection.1 }}
                                </span>
                            {{ form.b }}
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-xs-6">
                        <div class="input-group">
                             <span class="input-group-addon">
                                {{ form.selection.2 }}
                                </span>
                            {{ form.c }}
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-xs-6">
                        <div class="input-group">
                             <span class="input-group-addon">
                                {{ form.selection.3 }}
                                </span>
                            {{ form.d }}
                        </div>
                    </div>
                </div>
                <div class="form-group {% if form.keypoint.errors %} has-error {% endif %}">
                    <label class="control-label"
                           for="{% if form.keypoint.errors %} inputError1 {% endif %}">{{ form.keypoint.label }}</label>
                    {% if form.keypoint.errors %}
                        <span class="text-danger pull-right">{{ form.keypoint.errors }}</span>
                    {% endif %}
                    {{ form.keypoint }}
                    <br>
                    <input type="text" id="tags" class="form-control">
                    <p class="text-muted">{{ form.keypoint.help_text }}</p>
                </div>
                <div class="form-group row">
                    <div class="form-group {% if form.classname.errors %} has-error {% endif %}  col-xs-3 col-md-3">
                        <label class="control-label"
                               for="{% if form.classname.errors %} inputError1 {% endif %}">{{ form.classname.label }}</label>
                        {% if form.classname.errors %}
                            <span class="text-danger pull-right">{{ form.classname.errors }}</span>
                        {% endif %}
                        {{ form.classname }}
                        <p class="text-muted">{{ form.classname.help_text }}</p>
                    </div>


                    <div class="form-group col-xs-3 col-md-3">
                        <label class="control-label"
                               for="">一级知识点</label>
                        <select class="form-control" id="id_knowledgePoint1" name="knowledgePoint1">
                        </select>
                    </div>

                    <div class="form-group col-xs-3 col-md-3">
                        <label class="control-label"
                               for="">二级知识点</label>
                        <select class="form-control" id="id_knowledgePoint2" name="knowledgePoint2">
                        </select>
                    </div>
                    <div class="col-xs-3 col-md-3">
                        <br>
                        <button type="button" class="form-control btn btn-primary addkp">添加</button>
                    </div>
                </div>
                <br>
                <p>
                    <button type="submit" class="btn btn-success btn-lg">保存题目</button>
                </p>
            </form>
        </div>
    </div>
    <script>
        $.validate({
            validateOnBlur: false, // disable validation when input looses focus
            errorMessagePosition: 'top',// Instead of 'inline' which is default
            scrollToTopOnError: false // Set this property to true on longer forms
        });
        $("")
    </script>
    <script>
        $("[name='selection']").attr('required', 'required');
    </script>
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
        });
        jQuery(document).ready(function () {
            $("[name='classname']").change(function () {
                $("[name='knowledgePoint2']").empty();
                $("[name='knowledgePoint2']").append("<option value=\"0\">全部二级知识点</option>");
                $("[name='knowledgePoint1']").empty();
                $("[name='knowledgePoint1']").append("<option value=\"0\">全部一级知识点</option>");
                $.ajax({
                    type: "post",
                    url: "{% url 'select_point' %}",
                    dataType: "json",
                    data: {'course': $(this).val(), 'parent': 0},
                    success: function (data) {
                        for (var p in data) {
                            $("[name='knowledgePoint1']").append("<option value=\"" + p + "\">" + data [p] + "</option>");
                        }
                    }
                });
            });
            $("[name='knowledgePoint1']").change(function () {
                $("[name='knowledgePoint2']").empty();
                $("[name='knowledgePoint2']").append("<option value=\"0\">全部二级知识点</option>");
                $.ajax({
                    type: "post",
                    url: "{% url 'select_point' %}",
                    dataType: "json",
                    data: {'parent': $(this).val()},
                    success: function (data) {
                        for (var p in data) {
                            $("[name='knowledgePoint2']").append("<option value=\"" + p + "\">" + data [p] + "</option>");
                        }
                    }
                });
            });
        });
        var elt = $('#tags');
        elt.tagsinput({
            itemValue: 'value',
            itemText: 'text'
        });
        $(".addkp").click(function () {
            if ($('[name="knowledgePoint2"]').val() > 0) {
                var str = $('[name="classname"]').find("option:selected").text() + ' > ' + $('[name="knowledgePoint1"]').find("option:selected").text() + ' > ' + $('[name="knowledgePoint2"]').find("option:selected").text();
                elt.tagsinput('add', {'value': $('[name="knowledgePoint2"]').val(), 'text': str});
            }
        });

        elt.change(function () {
            $("#id_keypoint").val($(this).val());
        });

        var initVal = $("#id_keypoint").val();
        if (initVal) {
            json = JSON.parse(initVal);
            for (var key in json) {
                elt.tagsinput('add', {'value': key, 'text': json[key]});
            }
            $("#id_keypoint").val($(elt).val());
        }

        $.validate({});
    </script>
{% endblock %}

judge/templates/choice_problem_detail.html
{% extends 'base.html' %}
{% block extrahead %}
{% endblock %}
{% block content %}

    <p>
    <div class="btn-group">
        <a class="btn btn-primary btn-l" href="{% url 'choice_problem_list' %}" role="button">返回列表</a>
        <button type="button" class="btn btn-danger" id="delete" onclick="delete_item(self)">删除此题</button>
        <a class="btn btn-success btn-l" href="{% url 'update_choice_problem' problem.id %}"
           role="button">重新编辑</a>
    </div>
    </p>
    <table id="w0" class="table table-striped table-bordered detail-view table-hover ">
        <tbody>
        <tr>
            <th>题目ID</th>
            <td>{{ problem.id }}</td>
        </tr>
        <tr>
            <th>提干</th>
            <td>{{ problem.title }}</td>
        </tr>
        <tr>
            <th>知识点</th>
            <td>{{ knowledge_point }}</td>
        </tr>
        <tr>
            <th>选项A</th>
            <td>{{ problem.a }}</td>
        </tr>
        <tr>
            <th>选项B</th>
            <td>{{ problem.b }}</td>
        </tr>
        <tr>
            <th>选项C</th>
            <td>{{ problem.c }}</td>
        </tr>
        <tr>
            <th>选项D</th>
            <td>{{ problem.d }}</td>
        </tr>
        <tr>
            <th>正确选项</th>
            <td>{{ problem.right_answer|upper }}</td>
        </tr>
        <tr>
            <th>修改时间</th>
            <td>{{ problem.in_date }}</td>
        </tr>
        <tr>
            <th>创建者</th>
            <td>{{ problem.creater.first_name }}</td>
        </tr>
        <tr>
            <th>引用权限</th>
            <td>共享</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

judge/templates/choice_problem_list.html
{% extends 'base.html' %}
{% block extrahead %}
    {% load static %}
    <script src="{% static 'assets/js/bootstrap-table.min.js' %}"></script>
    <link href="{% static 'assets/css/bootstrap-table.min.css' %}" rel="stylesheet">
    <script src="{% static 'assets/js/bootstrap-table-zh-CN.min.js' %}"></script>
{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li class="active">题库管理</li>
        <li class="active">选择题列表</li>
    </ol>
    <h1>选择题题库</h1>
    <div class="btn-group">
        <button type="button" id="remove" class="btn btn-danger"><i class="glyphicon glyphicon-remove">删除选中</i></button>
        <a class="btn btn-primary btn-l" href="{% url 'add_choice_problem' %}" role="button"><i
                class="glyphicon glyphicon-plus">添加题目</i></a>
    </div>
    <div id="toolbar">
        <div class="form-inline" role="form">
            <div class="form-group">
                <select class="form-control" id="classname" name="classname">
                    <option value="0" selected="selected">全部课程</option>
                    {% for classname in classnames %}
                        <option value="{{ classname.pk }}">{{ classname.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <select class="form-control" id="id_knowledgePoint1" name="knowledgePoint1">
                    <option value="0" selected="selected">全部一级知识点</option>
                </select>
            </div>

            <div class="form-group">

                <select class="form-control" id="id_knowledgePoint2" name="knowledgePoint2">
                    <option value="0" selected="selected">全部二级知识点</option>
                </select>
            </div>
            <button id="ok" type="submit" class="btn btn-default">筛选</button>

        </div>
    </div>
    <table id="table"
           data-toggle="table"
           data-url="{% url 'get_json' 'ChoiceProblem' %}"
           data-side-pagination="server"
           data-pagination="true"
           data-page-list="[1, 20, 50, 100, 200]"
           data-classes="table table-hover table-condensed"
           data-toolbar="#toolbar"
           data-striped="true"
           data-query-params="queryParams"
           data-search="true"
    >
        <thead>
        <tr>
            <th data-field="state" data-checkbox="true"></th>
            <th data-field="pk" data-sortable="true" data-valign="middle">ID</th>
            <th data-field="title" data-sortable="true" data-valign="middle">题干</th>
            <th data-field="knowledge_point" data-valign="middle"> 知识点</th>
            <th data-field="update_date" data-sortable="true" data-valign="middle">最后修改日期</th>
            <th data-field="id" data-formatter="editFormatter" data-valign="middle">操作</th>
        </tr>
        </thead>
    </table>
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
        });
        var $table = $('#table');
        function editFormatter(value) {
            return '<a class="btn btn-primary btn-xs" href="{% url '_update_choice_problem' %}' + value + '/" title="编辑" aria-label="编辑" data-pjax="0"><span class="glyphicon glyphicon glyphicon-edit"></span></a>' + ' <a class="btn btn-success btn-xs" href="{% url '_choice_problem_detail' %}' + value + '/" title="查看" aria-label="查看" data-pjax="0"><span class="glyphicon glyphicon-eye-open"></span></a>';
        }
        $remove = $('#remove');

        $(function () {
            $remove.click(function () {
                var ids = $.map($table.bootstrapTable('getSelections'), function (row) {
                    return row.id;
                });
                if (ids.length > 0) {
                    if (confirm("确定要删除吗？")) {
                        $.ajax({
                            type: 'POST',
                            url: "{% url 'del_choice_problem' %}",
                            data: {'ids': ids},
                            success: function (data) {
                                if (data == 1) {
                                    $table.bootstrapTable('refresh');
                                    return false
                                } else {
                                    alert('删除失败');
                                }
                            },
                            error: function () {
                                alert("删除失败")
                            }
                        });
                    }
                } else {
                    alert('您尚未选择题目')
                }
            });
        });
        $ok = $('#ok');
        $(function () {
            $ok.click(function () {
                $table.bootstrapTable('refresh');
            });
        });
        function queryParams(params) {
            $('#toolbar').find('select[name]').each(function () {
                params[$(this).attr('name')] = $(this).val();
            });
            return params;
        }

    </script>
    <script>
        jQuery(document).ready(function () {
            $("[name='classname']").change(function () {
                $("[name='knowledgePoint2']").empty();
                $("[name='knowledgePoint2']").append("<option value=\"0\">全部二级知识点</option>");
                $("[name='knowledgePoint1']").empty();
                $("[name='knowledgePoint1']").append("<option value=\"0\">全部一级知识点</option>");
                $.ajax({
                    type: "post",
                    url: "{% url 'select_point' %}",
                    dataType: "json",
                    data: {'course': $(this).val(), 'parent': 0},
                    success: function (data) {
                        for (var p in data) {
                            $("[name='knowledgePoint1']").append("<option value=\"" + p + "\">" + data [p] + "</option>");
                        }
                    }
                });
            });
            $("[name='knowledgePoint1']").change(function () {
                $("[name='knowledgePoint2']").empty();
                $("[name='knowledgePoint2']").append("<option value=\"0\">全部二级知识点</option>");
                $.ajax({
                    type: "post",
                    url: "{% url 'select_point' %}",
                    dataType: "json",
                    data: {'parent': $(this).val()},
                    success: function (data) {
                        for (var p in data) {
                            $("[name='knowledgePoint2']").append("<option value=\"" + p + "\">" + data [p] + "</option>");
                        }
                    }
                });
            });
        })
    </script>
{% endblock %}