onlineTest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from judge.views import get_json

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='adminView'),
    url(r'^index/', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include('auth_system.urls')),
    url(r'^judge/', include('judge.urls')),
    url(r'^work/', include('work.urls')),
    url(r'get-json-(?P<model_name>\w+)/$', get_json,name='get_json'),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    
]

work/urls.py
from django.conf.urls import url, include

from work.views import add_homework, get_json_work, list_homework, del_homework, show_homework, \
    ajax_for_homework_info, do_homework, add_banji, add_courser, get_banji_list, list_banji, del_banji, update_banji, \
    copy_to_my_homework, list_my_homework, update_public_homework, update_my_homework, show_my_homework, show_banji, \
    add_students, ajax_add_students, assign_homework, list_do_homework, get_my_homework_todo, show_homework_result, \
    list_finished_homework, get_finished_homework, get_finished_students, list_coursers, list_kp1s, list_kp2s, \
    delete_courser, add_kp1, add_kp2, delete_kp1, delete_kp2, add_myhomework, test_run, delete_homeworkanswer, \
    rejudge_homework, save_homework_temp, init_homework_data, file_download

urlpatterns = [
    url(r'del-homeworkanswer-(?P<id>\d+)', delete_homeworkanswer, name='delete_homeworkanswer'),
    url(r'del-homeworkanswer-', delete_homeworkanswer, name='_delete_homeworkanswer'),
    url(r'add-homework$', add_homework, name='add_homework'),
    url(r'get-json-work', get_json_work, name='get_json_data'),
    url(r'^homework-list', list_homework, name='homework_list'),
    url(r'del-homework', del_homework, name='del_homework'),
    url(r'^homework-detail-$', show_homework, name='_homework_detail'),
    url(r'update-public-homework-$', update_public_homework, name='_update_public_homework'),
    url(r'update-my-homework-$', update_my_homework, name='_update_my_homework'),
    url(r'do_homework$', do_homework, name='_do_homework'),
    url(r'update-banji-$', update_banji, name='_update_banji'),
    url(r'my-homework-detail-$', show_my_homework, name='_my_homework_detail'),
    url(r'banji-detail-$', show_banji, name='_banji_detail'),
    url(r'add-students-to-mybanji-$', add_students, name='_add_students'),
    url(r'homework-result-$', show_homework_result, name='_show_homework_result'),
    url(r'^homework-detail-(?P<pk>\d+)/$', show_homework, name='homework_detail'),
    url(r'update-public-homework-(?P<pk>\d+)', update_public_homework, name='update_public_homework'),
    url(r'update-my-homework-(?P<pk>\d+)', update_my_homework, name='update_my_homework'),
    url(r'get_homework_info', ajax_for_homework_info, name='get_homework_info'),
    url(r'do_homework(?P<homework_id>\d+)', do_homework, name='do_homework'),
    url(r'add_banji', add_banji, name='add_banji'),
    url(r'add_courser', add_courser, name='add_courser'),
    url(r'get_banji_list', get_banji_list, name='get_banji_list'),
    url(r'banji-list', list_banji, name='banji_list'),
    url(r'del-banji', del_banji, name='del_banji'),
    url(r'update-banji-(?P<id>\d+)', update_banji, name='update_banji'),
    url(r'copy-to-myhomework', copy_to_my_homework, name='copy_to_my_homework'),
    url(r'my_homework_list', list_my_homework, name='my_homework_list'),
    url(r'my-homework-detail-(?P<pk>\d+)', show_my_homework, name='my_homework_detail'),
    url(r'banji-detail-(?P<pk>\d+)', show_banji, name='banji_detail'),
    url(r'add-students-to-mybanji-(?P<pk>\d+)', add_students, name='add_students'),
    url(r'add-students', ajax_add_students, name='ajax_add_students'),
    url(r'assign-homework', assign_homework, name='assign_homework'),
    url(r'do-homework-list', list_do_homework, name='list_do_homework'),
    url(r'get-do-homework-data', get_my_homework_todo, name='get_my_homework_todo'),
    url(r'homework-result-(?P<id>\d+)', show_homework_result, name='show_homework_result'),
    url(r'list-finished-homework', list_finished_homework, name='list_finished_homework'),
    url(r'get-finished-homework-list', get_finished_homework, name='get_finished_homework'),
    url(r'get-finished-student', get_finished_students, name="get_finished_students"),
    url(r'courser-list', list_coursers, name='list_coursers'),
    url(r'kp1-list-(?P<id>\d+)', list_kp1s, name='list_kp1s'),
    url(r'kp2-list-(?P<id>\d+)', list_kp2s, name='list_kp2s'),
    url(r'delete-courser', delete_courser, name='delete_courser'),
    url(r'add-kp1', add_kp1, name='add_kp1'),
    url(r'add-kp2', add_kp2, name='add_kp2'),
    url(r'delete-kp1', delete_kp1, name='delete_kp1'),
    url(r'delete-kp2', delete_kp2, name='delete_kp2'),
    url(r'add-myhomework', add_myhomework, name='add_myhomework'),
    url(r'test_run', test_run, name='test_run'),
    url(r'rejudge-homework-$', rejudge_homework, name='_rejudge_homework'),
    url(r'rejudge-homework-(?P<id>\d+)', rejudge_homework, name='rejudge_homework'),
    url(r'save-homework',save_homework_temp,name='save_homework'),
    url(r'get-init-homework-data',init_homework_data,name='get_init_homework_data'),
    url(r'download',file_download,name='download')
]

judge/models.py
from django.db import models

from auth_system.models import MyUser

# Create your models here.
from work.models import HomeworkAnswer, MyHomework


class ClassName(models.Model):
    name = models.CharField(verbose_name='课程名称', max_length=30)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'class_name'
        verbose_name = '课程名称'
        verbose_name_plural = '课程名称'


class KnowledgePoint1(models.Model):
    name = models.CharField(verbose_name='一级知识点名称', max_length=20)
    id = models.AutoField(primary_key=True)
    classname = models.ForeignKey(ClassName, verbose_name='所属课程')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'knowledge_point_1'
        verbose_name = '一级知识点'
        verbose_name_plural = '一级知识点'


class KnowledgePoint2(models.Model):
    name = models.CharField(verbose_name='二级知识点名称', max_length=20)
    upperPoint = models.ForeignKey(KnowledgePoint1, verbose_name='上级课程')
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'knowledge_point_2'
        verbose_name = '二级知识点'
        verbose_name_plural = '二级知识点'


class ChoiceProblem(models.Model):
    id = models.AutoField('选择题ID', primary_key=True)
    title = models.TextField(max_length=200)
    a = models.CharField(max_length=50)
    b = models.CharField(max_length=50)
    c = models.CharField(max_length=50)
    d = models.CharField(max_length=50)
    right_answer = models.CharField(max_length=1)
    creater = models.ForeignKey(MyUser)
    update_date = models.DateTimeField(auto_now=True, verbose_name='最后修改时间', blank=True, null=True)
    in_date = models.DateTimeField(auto_now_add=True)
    knowledgePoint1 = models.ManyToManyField(KnowledgePoint1, verbose_name='一级知识点')
    knowledgePoint2 = models.ManyToManyField(KnowledgePoint2, verbose_name='二级知识点')
    classname = models.ManyToManyField(ClassName, verbose_name='所属课程')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['id']
        verbose_name = '选择题'
        verbose_name_plural = '选择题'


class Problem(models.Model):
    problem_id = models.AutoField('题目id', primary_key=True)
    title = models.CharField(verbose_name='标题', max_length=200)
    description = models.TextField('描述', blank=True, null=True)
    input = models.TextField('输入描述', blank=True, null=True)
    output = models.TextField('输出描述', blank=True, null=True)
    sample_input = models.TextField('样例输入1', blank=True, null=True)
    sample_output = models.TextField('样例输出1', blank=True, null=True)
    sample_input2 = models.TextField('样例输入2', blank=True, null=True)
    sample_output2 = models.TextField('样例输出2', blank=True, null=True)
    spj = models.CharField(max_length=1, default=0)
    hint = models.TextField(blank=True, null=True)
    source = models.CharField(max_length=100, blank=True, null=True)
    in_date = models.DateTimeField('录入时间', blank=True, null=True, auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True, verbose_name='最后修改时间', blank=True, null=True)
    time_limit = models.IntegerField('限制时间', default=1)
    memory_limit = models.IntegerField('限制内存', default=128)
    defunct = models.CharField(max_length=1, default='N')
    accepted = models.IntegerField('AC数量', blank=True, null=True, default=0)
    submit = models.IntegerField('提交数量', blank=True, null=True, default=0)
    solved = models.IntegerField(blank=True, null=True)
    knowledgePoint1 = models.ManyToManyField(KnowledgePoint1, verbose_name='一级知识点')
    knowledgePoint2 = models.ManyToManyField(KnowledgePoint2, verbose_name='二级知识点')
    classname = models.ManyToManyField(ClassName, verbose_name='所属课程')
    creater = models.ForeignKey(MyUser)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'problem'
        ordering = ['problem_id']
        verbose_name = '编程题'
        verbose_name_plural = '编程题'


class Runtimeinfo(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    error = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'runtimeinfo'


class Solution(models.Model):
    solution_id = models.AutoField(primary_key=True)
    problem_id = models.IntegerField()
    user_id = models.CharField(max_length=48)
    time = models.IntegerField(default=0)
    memory = models.IntegerField(default=0)
    in_date = models.DateTimeField(auto_now_add=True)
    result = models.SmallIntegerField(default=0)
    language = models.IntegerField(default=0)
    ip = models.CharField(max_length=15)
    contest_id = models.IntegerField(blank=True, null=True)
    valid = models.IntegerField(default=1)
    num = models.IntegerField(default=-1)
    code_length = models.IntegerField(default=0)
    judgetime = models.DateTimeField(blank=True, null=True)
    pass_rate = models.DecimalField(max_digits=2, decimal_places=2, default=0.00)
    lint_error = models.IntegerField(default=0)
    homework_answer = models.ForeignKey(HomeworkAnswer, null=True)
    oi_info = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'solution'

    def __str__(self):
        try:
            return str(self.homework_answer.id)
        except:
            return 'none'


class SourceCode(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    source = models.TextField()

    class Meta:
        db_table = 'source_code'

    def __str__(self):
        return str(self.solution_id)


class SourceCodeUser(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    source = models.TextField()

    class Meta:
        db_table = 'source_code_user'


class Compileinfo(models.Model):
    solution_id = models.IntegerField(primary_key=True)
    error = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'compileinfo'

work/models.py
from django.db import models

from auth_system.models import MyUser


class BanJi(models.Model):
    """
    班级
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40, verbose_name='班级名称')
    teacher = models.ForeignKey(MyUser, null=True, related_name='banJi_teacher')
    students = models.ManyToManyField(MyUser, related_name='banJi_students')
    courser = models.ForeignKey('judge.ClassName', null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return str(self.name)


class HomeWork(models.Model):
    """
    公共作业
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    courser = models.ForeignKey('judge.ClassName', verbose_name='所属课程')
    creater = models.ForeignKey(MyUser, verbose_name='创建者')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    problem_ids = models.CharField(max_length=200, verbose_name='编程题列表id列表')
    choice_problem_ids = models.CharField(max_length=200, verbose_name='选择题id列表')
    problem_info = models.TextField()
    choice_problem_info = models.TextField()
    allowed_languages = models.CharField(max_length=50)
    total_score = models.IntegerField()

    def __str__(self):
        return str(self.id)


class MyHomework(models.Model):
    """
    私有作业
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40)
    courser = models.ForeignKey('judge.ClassName', verbose_name='所属课程')
    creater = models.ForeignKey(MyUser, verbose_name='创建者')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    problem_ids = models.CharField(max_length=200, verbose_name='编程题列表id列表', null=True, blank=True)
    choice_problem_ids = models.CharField(max_length=200, verbose_name='选择题id列表', null=True, blank=True)
    problem_info = models.TextField(null=True, blank=True)
    choice_problem_info = models.TextField(null=True, blank=True)
    allowed_languages = models.CharField(max_length=50)
    banji = models.ManyToManyField(BanJi)
    finished_students = models.ManyToManyField(MyUser, related_name='finished_students', null=True, blank=True)
    allow_resubmit = models.BooleanField(default=False, verbose_name='是否允许重复提交作业？')
    total_score = models.IntegerField()

    def __str__(self):
        return str(self.id)


class HomeworkAnswer(models.Model):
    """
    保存用户提交作业后的相关信息
    """
    id = models.AutoField(primary_key=True)
    homework = models.ForeignKey(MyHomework, null=True, verbose_name='作业')
    creator = models.ForeignKey(MyUser, null=True, verbose_name='答题者')
    wrong_choice_problems = models.CharField(max_length=200, null=False, verbose_name='错误的选择题', default='')  #
    wrong_choice_problems_info = models.CharField(max_length=200, null=False, verbose_name='错误的选择题保留信息', default='')
    score = models.IntegerField(null=False, verbose_name='总成绩', default=0)
    choice_problem_score = models.IntegerField(null=False, verbose_name='选择题成绩', default=0)
    problem_score = models.IntegerField(null=False, verbose_name='编程题成绩', default=0)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='答题时间')
    judged = models.BooleanField(default=False, verbose_name='是否已经判分？')

    def __str__(self):
        return str(self.id)


class TempHomeworkAnswer(models.Model):
    """暂存表单数据"""
    id = models.AutoField(primary_key=True)
    homework = models.ForeignKey(MyHomework)
    creator = models.ForeignKey(MyUser)
    data = models.TextField(null=True)

work/forms.py
from django import forms


class TestForm(forms.Form):
    problem_id = forms.IntegerField()
    code = forms.TimeField(widget=forms.Textarea)

work/templates/add_courser.html
{% extends 'base.html' %}
{% block title %}添加课程{% endblock %}
{% block extrahead %}
    {% load static %}
    <script src="{% static 'assets/js/moment/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/moment/zh-cn.js' %}"></script>
    <link href="{% static 'assets/css/bootstrap-editable.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap-datetimepicker.min.css' %}"
          rel="stylesheet">
    <script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li class="active">课程管理</li>
        <li class="active">添加课程</li>
    </ol>
    <h1>添加课程</h1>
    <form id="homework-add-form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">课程名称</label>
            <input type="text" class="form-control" id="name" placeholder="作业名称" required="required" name="name">
        </div>
        <button type="submit" class="btn btn-default" onclick="check()">保存</button>
    </form>
{% endblock %}

work/templates/add_students.html
{% extends 'base.html' %}
{% block title %}批量添加学生{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li class="active"><a href="{% url 'banji_list' %}">班级管理</a></li>
        <li class="active">批量添加学生到班级</li>
    </ol>
    <h3>批量添加学生账号</h3>
    <form>
        <input type="hidden" name="banji_id" id="banji_id" value="{{ id }}">
        <p><textarea name="stu_detail" id="stu_detail" class="form-control" rows="10"
                     placeholder="学生账号信息格式为：一行一个学生，每行的前两个字段是学号和真实姓名，初始密码同用户名，初始邮箱为南邮邮箱，字段之间用空格分隔"></textarea>
        <p><input type="button" class="btn btn-primary" name="submit_stu" id="submit_stu" value="提交学生账号信息"/>
    </form>

    <style type="text/css">
        .modal-body {
            height: 300px;
            overflow: auto;
        }
    </style>


    <div id="modal_result" class="fade modal" role="dialog" tabindex="-1" data-backdrop="static">
        <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">批量添加学生账号</h4>
                </div>
                <div class="modal-body">
                    批量添加学生账号信息的操作可能会耗费比较长的时间，请耐心等待……<br/><br/>
                    <div id="result" name="result"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        dataPara = null;
        count = 0;
        $(function () {
            $("#submit_stu").click(function () {
                $('#result').html("");
                $('#modal_result').modal('show');
                dataPara = $("#stu_detail").val().split("\n");
                count = 0;
                setTimeout(adduser, 0);
            });

            function adduser() {
                if (dataPara.length > 0) {
                    stu = $.trim(dataPara.shift());
                    if (stu.length > 0) {
                        $.ajax({
                            type: "post",
                            url: "{% url 'ajax_add_students' %}",
                            dataType: "json",
                            data: {stu_detail: stu, banji_id: $("#banji_id").val()},
                            success: function (data) {
                                if (data.result == 0) {
                                    if (data.count > 0) {
                                        $("#result").append("添加学生 " + stu + " 到本班级：<font color=green>成功</font><br/>");
                                        count++;
                                    } else {
                                        $("#result").append("添加学生 " + stu + " 到本班级：<font color=red>失败：" + data.message + "</font><br/>");
                                    }
                                    setTimeout(adduser, 0);
                                } else {
                                    alert({
                                        text: '信息提交过程中遇到错误：' + data.message + '！',
                                        type: 'danger',
                                        position: 'top-center'
                                    });
                                }
                                //alert(data);
                            },
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                alert({text: '保存数据时发生错误！', type: 'danger', position: 'top-center'});
                                //alert(errorThrown);
                            }
                        });
                    } else {
                        setTimeout(adduser, 0);
                    }
                } else {
                    $("#result").append("<br/>批量添加学生账号信息完毕，共添加" + count + "位学生。");
                }
            };
        });
    </script>
{% endblock %}

work/templates/banji_add.html
{% extends 'base.html' %}
{% block extrahead %}
    {% load static %}
    <script src="{% static 'assets/js/moment/moment.min.js' %}"></script>
    <script src="{% static 'assets/js/moment/zh-cn.js' %}"></script>
    <link href="{% static 'assets/css/bootstrap-editable.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap-datetimepicker.min.css' %}"
          rel="stylesheet">
    <script src="{% static 'assets/js/bootstrap-datetimepicker.min.js' %}"></script>
{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li class="active"><a href="{% url 'banji_list' %}">班级管理</a></li>
        <li class="active">{{ title }}</li>
    </ol>
    <h1>{{ title }}</h1>
    <form id="homework-add-form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">班级名称</label>
            <input type="text" class="form-control" id="name" placeholder="班级名称" required="required" name="name">
        </div>

        <div class="form-group">
            <label for="classname">所属课程</label>
            <select class="form-control" id="classname" name="classname">
                {% for classname in classnames %}
                    <option value="{{ classname.pk }}">{{ classname.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <label for="start_time">开始时间</label>
                    <div class='input-group date' id='datetimepicker1'>
                        <input type='text' class="form-control" name="start_time" id="start_time"/>
                        <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                </div>
            </div>
            <div class='col-sm-6'>
                <div class="form-group">
                    <label for="end_time">结束时间</label>
                    <div class='input-group date' id='datetimepicker2'>
                        <input type='text' class="form-control" name="end_time" id="end_time"/>
                        <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-default" onclick="check()">保存</button>
    </form>

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker(
                    {
                        format: 'YYYY-MM-DD HH:mm:ss',
                        sideBySide: true,
                        defaultDate: moment()
                    }
            );
        });
        $(function () {
            $('#datetimepicker2').datetimepicker(
                    {
                        format: 'YYYY-MM-DD HH:mm:ss', sideBySide: true,
                        defaultDate: moment("23:59:59", "HH-mm-ss").add(7, 'days')
                    }
            )
            ;
        });
    </script>
    <script>
        if (window.location.pathname.indexOf('add_banji') == -1) {
            setTimeout(function () {
                $("#name").val('{{ name }}');
                $('#datetimepicker1').data("DateTimePicker").date('{{ start_time }}');
                $('#datetimepicker2').data("DateTimePicker").date('{{ end_time }}');
                $("#classname option[value='{{ courser_id }}']").attr("selected", true);
            })
        }
    </script>
{% endblock %}

work/templates/banji_detail.html
{% extends 'base.html' %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li class="active"><a href="{% url 'banji_list' %}">班级管理</a></li>
        <li class="active">{{ title }}</li>
    </ol>
    <p>
    <div class="btn-group">
        <a class="btn btn-primary btn-l" href="{% url 'banji_list' %}" role="button">返回班级列表</a>
        <a class="btn btn-success btn-l" href="{% url 'update_banji' id %}"
           role="button">重新编辑</a>
        <a class="btn btn-info btn-l" href="{% url 'add_students' id %}">添加学生到班级</a>
    </div>
    </p>
    <table id="w0" class="table table-striped table-bordered detail-view table-hover ">
        <tbody>
        <tr>
            <th>班级名称</th>
            <td>{{ name }}</td>
        </tr>
        <tr>
            <th>负责老师</th>
            <td>{{ teacher }}</td>
        </tr>
        <tr>
            <th>所属课程</th>
            <td>{{ courser }}</td>
        </tr>

        <tr>
            <th>开始时间</th>
            <td>{{ start_time }}</td>
        </tr>
        <tr>
            <th>结束时间</th>
            <td>{{ end_time }}秒</td>
        </tr>
        <tr>
            <th>该班级的学生</th>

            <td>{% for student in students %}
                {{ student.id_num }}
                {{ student.username }}<br>
            {% endfor %}</td>


        </tr>

        </tbody>
    </table>

{% endblock %}

work/templates/kp1_list.html
{% extends 'base.html' %}
{% block extrahead %}
    {% load static %}
    <script src="{% static 'assets/js/jquery-confirm.min.js' %}"></script>
    <link href="{% static 'assets/css/jquery-confirm.min.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">主页</a></li>
        <li><a href="{% url 'list_coursers' %}">课程管理</a></li>
        <li class="active">一级知识点列表</li>
    </ol>
    <button type="button" class="btn btn-success" onclick="add_kp1()">添加一级知识点</button>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>名称</th>
            <th>二级知识点数量</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for kp1 in kp1s %}
            <tr>
                <th><a href="{% url 'list_kp2s' kp1.id %}">{{ kp1.name }}</a></th>
                <th>{{ kp1.knowledgepoint2_set.count }}</th>
                <th>
                    <button type="button" class="btn btn-danger btn-xs"
                            onclick="del_kp1({{ kp1.id }})"><span class="glyphicon glyphicon-trash"
                                                                  aria-hidden="true"></span></button>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <script>
        function add_kp1() {
            $.confirm({
                title: '新建知识点',
                content: '请输入一级知识点名称 <input class="form-control" id="kp1_name" type="text" placeholder="输入知识点名称"/>',
                confirm: function () {
                    $.ajax({
                        url: '{% url 'add_kp1' %}',
                        dataType: 'json',
                        method: 'post',
                        data: {'id': {{ id }}, 'name': $('#kp1_name').val()}
                    }).done(function (response) {
                        if (response == 1) {
                            $.alert('创建成功！');
                            location.reload();
                            return true
                        } else {
                            self.setContent('创建时出现问题');
                            return false
                        }
                    }).fail(function () {
                        self.setContent('数据传输时出现问题');
                        return false
                    });
                }
            });
        }
        function del_kp1(id) {
            $.confirm({
                content: '确定要删除这个知识点吗？',
                title: '确认删除',
                confirmButton: '我确认',
                cancelButton: '取消',
                confirm: function () {
                    $.ajax({
                        url: '{% url 'delete_kp1' %}',
                        dataType: 'json',
                        method: 'post',
                        data: {'id': id}
                    }).done(function (response) {
                        if (response == 1) {
                            location.reload();
                            return true
                        } else {
                            self.setContent('删除时出现问题');
                            return false
                        }
                    }).fail(function () {
                        self.setContent('数据传输时出现问题');
                        return false
                    });
                }
            });
        }

    </script>
{% endblock %}